### ISSUE TITLE
Disable on certain programs - copying a textbox on Powerpoint makes it into an image

### ISSUE THREAD

**Issue by DanielePessina** [FuzzyIdeas/Clop#1]
Copying a textbox or item on Powerpoint makes it paste as an image, therefore I have to quit Clop. Would be useful to be able to exclude certain apps from triggering clop.

**Comment by alin23** [comment]
I have just added detection for PowerPoint to ignore data objects copied inside it. Re-download the app from https://lowtechguys.com/clop to update.
