### ISSUE TITLE
PNGs are converted to JPG 

### ISSUE THREAD

**Issue by klickreflex** [FuzzyIdeas/Clop#11]
Instead of optimizing PNG files, Clop creates a JPG version of my PNG files. I tried both, the direct download version and from Version 2.4.0 via Setapp (on M1).

Format settings are left to default (though I don't even see an option to deliberatley convert all png to jpg.
![CleanShot 2023-11-30 at 09 24 40@2x](https://github.com/FuzzyIdeas/Clop/assets/435825/058dea8e-974d-4e88-9f8d-46ffe0baa5a3)

**Comment by alin23** [comment]
There is an **Adaptive Optimization** setting right above those settings you have screenshotted. It chooses the smallest out of the resulting optimized PNG and JPEG files.
