### ISSUE TITLE
Finder funniness

### ISSUE THREAD

**Issue by mac2net** [FuzzyIdeas/Clop#12]
You had me there for a few minutes. I ran Clop through the Apple Services Menu and realised there is nothing in the Finder to tell me anything happened because the **Date Modified** doesn't change. The only way to tell is the **Date Last Opened** is wiped out and so is the **Tag**. To me this is a bug not a feature.

**Comment by alin23** [comment]
Well, it is actually a feature that a lot of people requested to be on by default :) you're free to turn it off

<img width="706" alt="Clop-005239-Monday-07-59" src="https://github.com/FuzzyIdeas/Clop/assets/3819725/d1ed0e7a-0b46-496a-bd6a-510d7c21ac2f">

**Comment by mac2net** [comment]
Thanks.
I can see why, but never saw this as a feature since pulling out the battery on an old Mac reset the year to 1904
