### ISSUE TITLE
Wrong link to your License

### ISSUE THREAD

**Issue by n2o** [FuzzyIdeas/Clop#15]
Just found this product, I am really interested in using it, thanks!

On your website https://lowtechguys.com/clop/ the link to GPLv3 is broken. Here's a screenshot, which was optimized with Clop:

<img width="1163" alt="image" src="https://github.com/FuzzyIdeas/Clop/assets/1507474/830c4195-47ae-4723-a88c-3e0f7b53ad34">

**Comment by alin23** [comment]
My bad, this should be fixed now :)
