### ISSUE TITLE
Optimization failed

### ISSUE THREAD

**Issue by kitze** [FuzzyIdeas/Clop#16]
Hey,

Great app!

I'm trying to optimize an mp4 file, and it doesn't matter if it's big or small I always get "Optimisation failed"

Any ideas what can be the problem?

**Comment by kitze** [comment]
After killing the app and restarting it, it works fine. Thanks for the amazing app.

**Comment by alin23** [comment]
Hey @kitze nice seeing you again 😊 glad it finally worked, could have been a filesystem permission issue. Let me know if the app needs any polish on your specific use cases.
