### ISSUE TITLE
The location of the pop-up window is uncomfortable

### ISSUE THREAD

**Issue by Awyugan** [FuzzyIdeas/Clop#17]
The pop-up window is located in the four corners. When I want to actively drag the image to compress it, the screen is too large and it is difficult to use the touchpad.

**Comment by alin23** [comment]
OK, thanks for the report! Where would it make sense to appear?

**Comment by Awyugan** [comment]
> OK, thanks for the report! Where would it make sense to appear?

Thanks for the reply, I have a few ideas.

1. Place it near the mouse, which may cause some inconvenience.
2. Select the file and right-click to pop up the clop option.
3. Use shortcut keys to quickly place clop.

**Comment by Awyugan** [comment]
This is great, thank you for explaining it!

**Comment by Awyugan** [comment]
Did you find a small problem when using clop? When converting jpeg or png, clop will use two sets of logic to export the image. If you want to directly replace the original file, another replacement cost will be added.

Solution: You can only choose to place it in another document and then delete the original file.

Usage scenario: screenshots in the course, when batch compression is required.

**Comment by kanchi240** [comment]
> Did you find a small problem when using clop? When converting jpeg or png, clop will use two sets of logic to export the image. If you want to directly replace the original file, another replacement cost will be added.
> 
> Solution: You can only choose to place it in another document and then delete the original file.
> 
> Usage scenario: screenshots in the course, when batch compression is required.

I found there are backup files and converted files in these folders:
/private/tmp/backups
/private/tmp/clop/images
/private/tmp/clop/pdfs

Could it possible add a feature that do not backup original and converted files? Thanks.
@alin23

**Comment by alin23** [comment]
@kanchi240 No it's not possible, those files are needed as input files for optimizing, cropping and downscaling. They will get deleted automatically on next reboot. 

@Awyugan I'm not sure I understand the problem, but you can make another issue for that to explain it better. This one seems solved.

**Comment by kanchi240** [comment]
Thanks for explaining, btw 'next reboot' means reboot Clop or reboot Mac? My Mac never reboot except upgrade os.

**Comment by alin23** [comment]
> Thanks for explaining, btw 'next reboot' means reboot Clop or reboot Mac? My Mac never reboot except upgrade os.

Mac reboot. I also only update on OS upgrade, but seems to be often enough for me to clean those backups.

If the system starts running out of space, it will also start cleaning up older files from those folders automatically.
