### ISSUE TITLE
Feature Request: Crop videos

### ISSUE THREAD

**Issue by 3x071c** [FuzzyIdeas/Clop#21]
First off, loving the app so far and have used it to replace ImageOptim & Handbrake in my workflow (not sure about PDF Squeezer yet). Anyway, I was thinking it would be a really useful feature to be able to crop video directly in Clop (via the right-click context menu). Currently, I need to go through Apple Photos (Right Click -> Share -> Add to Photos, Photos -> Edit -> Crop, Photos -> File -> Export -> Export 1 Video) in a very tedious process just to be able to crop a clip natively. Would it be possible to introduce that as a feature?

**Comment by alin23** [comment]
Hi! Thank you for the kind words 😊 

You can already crop a video :)

Click on the resolution at the bottom of the thumbnail to crop to a specific size, or just click on (-) Minus button if you want to downscale it without changing its aspect ratio.

**Comment by 3x071c** [comment]
@alin23 Ah nice, thanks. Looks like it currently requires manual input for the exact dimensions. Don't know if that exceeds the scope of this project, but a visual cropping tool would be much appreciated! Cool stuff.
