### ISSUE TITLE
Feature Request: Optional guetzli image compression

### ISSUE THREAD

**Issue by 3x071c** [FuzzyIdeas/Clop#22]
ImageOptim has an option to use [guetzli](https://github.com/google/guetzli) compression, which is pretty slow, but produces noticeably smaller (lossless) files. Would be great if a feature could be added to Clop to (optionally) compress with guetzli instead.

**Comment by alin23** [comment]
Thanks for the request!

I'm happy enough with jpegoptim's speed-to-compression ratio. I don't want to be the next ImageOptim, Clop should be simpler and less configurable in my view. 

So I'll pass on guetzli.
