### ISSUE TITLE
PDF compression: Chinese text becomes garbled

### ISSUE THREAD

**Issue by kanchi240** [FuzzyIdeas/Clop#23]
HI!

I'm encountering an issue while using the compression tool to compress PDF documents saved from Safari. The web pages are in Chinese language. After compressing the PDF, copying the text from within the document and pasting it results in garbled characters. Additionally, the PDF is not searchable for Chinese text. However, searching and copying English text within the PDF works fine.

**Comment by alin23** [comment]
Unfortunately there is no possible fix for this. It happens because the PDF was created in such a way to disallow edits and tampering to the file, and it is not Chinese specific. I've had it happen with English as well.

**Comment by kanchi240** [comment]
Okay, I tested several other Chinese web pages and saved them as PDFs in Safari. I set the encoding to UTF-8 in Safari, but still has this problem. Thanks for your reply.
