### ISSUE TITLE
Frustrating Image Copying Issue - Why Does It Copy the File Path Instead?

### ISSUE THREAD

**Issue by Monti213** [FuzzyIdeas/Clop#24]
When copying image files, instead of the actual image being copied to the clipboard, I receive a file path such as /tmp/clop/images/94216.png. This behavior is highly frustrating

**Comment by alin23** [comment]
Both the image and the path are copied, and if the app you're pasting into doesn't support image pasting, it will get the file path instead (the pasting behaviour is what macOS does, not Clop). You can check that using an app like Clipboard Viewer:

![Clipboard Viewer-005990-Tuesday-22-08](https://github.com/FuzzyIdeas/Clop/assets/3819725/288c31f4-ac5a-4c8a-8138-7d823152fb08)

You can disable path copying so you only get the image if you want, there's a setting for that:

![Clop-005992-Tuesday-22-09](https://github.com/FuzzyIdeas/Clop/assets/3819725/171e745d-fce3-4beb-9abe-78cc8cbf217f)
