### ISSUE TITLE
Disable Floating Results For Image Auto-Optimizer

### ISSUE THREAD

**Issue by DmacMcgreg** [FuzzyIdeas/Clop#26]
First of all, want to say this is one of my favourite apps! Simple idea, and near flawless execution!

Right now I'm using this to optimize a constant flow of image screenshots of my screen. This results in Clop popping up every few seconds with new results..
Can we add an option per-folder to not show the results and just have it work silently in the background?

**Comment by alin23** [comment]
Thank you! 

Interesting use case. Is this like a home made Rewind.ai ?

I'll look into it, could be easy enough to add. 

Hint: you can use ffmpeg to compress all the images a lot more into an efficient HEVC video stream:

```sh
# let's say you're inside a folder with images named "image_000001.png"

ffmpeg -f image2 -framerate 30 -i image_%06d.png -vcodec hevc_ videotoolbox -tag:v hvc1 -q:v 40 image_stream.mp4
```

You can play with the quality value `-q:v` to get better quality or better compression. Larger numbers mean better quality but more file size.

**Comment by DmacMcgreg** [comment]
Exactly, theres a few OpenSource ones floating around on the internet these days.

Also that could be a great idea, I'll send it to the maintainers.

**Comment by alin23** [comment]
This can now be done in [v2.6.0](https://github.com/FuzzyIdeas/Clop/releases/tag/v2.6.0):

![Clop-006425-Monday-18-26](https://github.com/user-attachments/assets/e3c96c90-b832-4fdf-a2b9-7418a1318d43)

**Comment by DmacMcgreg** [comment]
Amazing, still one of my favourite apps. Appreciate you all!

**Comment by DmacMcgreg** [comment]
Any chance that the floating results could be turned on per-folder?
Its still nice to show floating results when using clipboard optimization.

**Comment by alin23** [comment]
Per-folder settings are in my todo list, but I really need a break now. I hope to get to it soon.  Thanks for the kind words!
