### ISSUE TITLE
Is it possible to turn off for specific applications (eg. keynote)?

### ISSUE THREAD

**Issue by geofflikesmusic** [FuzzyIdeas/Clop#27]
Hi,

Is it possible to turn off clop for certain apps, I use keynote a lot and it messes with some of the shapes and turns them into image files. I love using clop, but I sadly can't use the automation function until i can specify it to ignore certain apps.

**Comment by alin23** [comment]
There is no such option, but I'm always working on ignoring specific apps by default. Looks like Keynote uses `com.apple.iWork` as the prefix so I'll just ignore clipboard optimisation when I encounter that.

This will be released soon in v2.6.0

**Comment by alin23** [comment]
This is finally fixed in [v2.6.0](https://github.com/FuzzyIdeas/Clop/releases/tag/v2.6.0)
