### ISSUE TITLE
Toggle clipboard optimizer on/off?

### ISSUE THREAD

**Issue by ariktatishev** [FuzzyIdeas/Clop#28]
Is there a shortcut to activate clipboard optimizer on or off? There are times when I just want to pause Clop when I'm copying several times in a row. I know there's a "pause for the next copy" but I'd find it very useful for my workflow to just toggle it on or off completely since I'm doing more than one copy.

**Comment by alin23** [comment]
There is a **Pause automatic optimisations** item in the Clop menu but it does not have a keyboard shortcut. I'll add one in the next version.
