### ISSUE TITLE
Cannot find X in scope

### ISSUE THREAD

**Issue by dmoena** [FuzzyIdeas/Clop#3]
Hello! Noob here, so I might be reporting something very basic.
I'm getting several errors. Most of them, "Cannot find X in scope", where X is Regex, Window and SMAppService.
My guest is I'm missing some dependency, but as I said, I'm new to Mac App development.

Thanks for sharing! I'm using this as a learning project and plan to make some changes (would not say improvements yet)

**Comment by alin23** [comment]
Hi 👋 

Clop only works on macOS Ventura 13.0 or later. 

Sounds like you're compiling with an older toolchain. Those missing APIs were introduced in macOS 13.0 with Xcode 14.

**Comment by dmoena** [comment]
Thank you for answering!
Actually, I'm using exactly what you said. macOS Ventura 13.0.1 on M1 processor and Xcode 14.0.1

I'll keep digging. Now at least I'm OK from the OS and Xcode point of view.

Thanks!

**Comment by alin23** [comment]
Hmm that's odd. Clop has zero dependencies, it only relies on what the system provides, so it's definitely not something that hasn't downloaded etc.

It might be that the toolchain is pointed to an older version.

![image](https://user-images.githubusercontent.com/3819725/203118947-a6025dc6-2f75-44e6-afdc-7ae355953bca.png)

Or maybe check if `xcode-select` is configured correctly:

![image](https://user-images.githubusercontent.com/3819725/203119162-9b3bc21d-723c-4c30-8cf1-f0efae4a1d07.png)

**Comment by dmoena** [comment]
Thanks! I had Xcode 14.0.1 After updating to 14.1 it worked.
Thanks you guys!
