### ISSUE TITLE
[FEATURE] Drop shelf

### ISSUE THREAD

**Issue by Romachamp** [FuzzyIdeas/Clop#30]
Hello, I daily use Clop for optimising different files, but there is already built in functionality in the app, that, in my opinion, could be extended. When I select a file and then start dragging it, clop appears in the corner just like Yoink or DropOver shelf, when I drag files there, it optimises them. 

However, you could add a feature called drop shelf, so when I drag a file clop can either optimise it, or put in the shelf, where I can drop more files, and then either move them to another folder and optimise or optimise with one click, as a quick action similar to DropOver. 

This single feature will not only extend optimising possibilities of Clop, but also make it a potential competitor or successor to apps like Yoink, DropOver. 

Please, consider adding this feature. 

Thank you, in advance!

**Comment by alin23** [comment]
Hi @Romachamp 

Thanks you for the feature request! Although, I don't want to compete with Yoink and Dropover. I actually happily use Yoink in combination with Clop, they do very different things and Yoink is very good at that functionality.

Sorry for the letdown but I don't want to get into the "file shelf" space. Clop is strictly an optimiser, the drop zone is just one of the ways to optimise files, it is not its main feature. The main feature is automatic optimisations and I am working on extending automations at the moment.

**Comment by Jason-K** [comment]
@alin23 - do you mind sharing how you integrate clop with dropshelf?

**Comment by alin23** [comment]
> [@alin23](https://github.com/alin23) - do you mind sharing how you integrate clop with dropshelf?

It's all here: https://github.com/FuzzyIdeas/Clop/blob/838281d595d2ed5731e955eb981832101fe46c0a/Clop/Uploads.swift#L138-L150

Basically, these apps (Dropshare, Yoink, Dockside etc.) support opening files inside them which in turn adds the file to the shelf or uploads the file.

It's the same as doing this in a terminal:

```sh
open -a Dropshare /path/to/file-that-you-want-to-upload
```
