### ISSUE TITLE
Optimization of videos with multiple audio tracks

### ISSUE THREAD

**Issue by TimmBerg** [FuzzyIdeas/Clop#34]
Hi,

**Use case:** I do quite a bit of screen recordings with one audio track for computer audio and another audio track for the microphone.

**Problem:** Currently there is no option (that I am aware of) to keep all audio tracks of a video. Only the first one remains after the re-encoding.

**Suggested solution:** Adding an option to keep all audio tracks of a video.

Thank you so much, I really like Clop and use it frequently, so I would be happy to see this implemented, as it would enable me to use the video optimization for a lot more use cases!

**Comment by alin23** [comment]
I guess this should be the default. I wasn't aware ffmpeg only keeps one track by default. I'll look into it.

**Comment by alin23** [comment]
Fixed in [v2.6.1](https://github.com/FuzzyIdeas/Clop/releases/tag/v2.6.1)
