### ISSUE TITLE
How to use with CLI?

### ISSUE THREAD

**Issue by Hugo-Persson** [FuzzyIdeas/Clop#35]
Hi!

Is it possible to run Clop with CLI options? Or is it possible to bulk format files with regex pattern?

**Comment by alin23** [comment]
Sure! Install the Clop CLI from the menu bar icon of Clop then in the terminal run `clop --help` to see what it can do. 

To optimise multiple images with a pattern you can use shell expansion like so:

```
clop optimise *.png
```

If you want more complex matching you can use the `fd` tool to find files based on regex and act on them with clop. 

Something like:

```
brew install fd
fd img\d+\.png -x clop optimise
```

**Comment by Hugo-Persson** [comment]
Alright, thank you so much! Did not see the option in the menu bar

**Comment by AnirudhG07** [comment]
@alin23 any plans on publishing clop CLI itself somewhere rather than through the GUI?
It would also  be nice to have CLOP for linux command line as well. Do you any plans for this?

**Comment by alin23** [comment]
It's possible I didn't explain it well enough: **there is no CLI**. 

The CLI is just a terminal interface for the Clop macOS app, it doesn't do anything without the app. It's not possible to port it on Linux. 

Anyway, behind the scenes, Clop uses other open source CLI utilities which you can already use on Linux:

- jpegoptim for JPEGs
- pngquant for PNGs
- gifsicle for GIFs
- ffmpeg for videos
- Ghostscript for PDFs
- cwebp for WEBP

**Comment by AnirudhG07** [comment]
Right got it. Thanks for the info!
