### ISSUE TITLE
Automatic conversion to `webp`

### ISSUE THREAD

**Issue by hyperphysin** [FuzzyIdeas/Clop#36]
bc I love webp which has smaller size

**Comment by alin23** [comment]
You can do that, there's a format selector at the bottom of every optimization result which includes webp. 

You can also automate this from the Automation tab of Clop's settings by creating an image shortcut that uses the Convert to WEBP action, and set that shortcut to run on clipboard or folders.

**Comment by hyperphysin** [comment]
> You can do that, there's a format selector at the bottom of every optimization result which includes webp.
> 
> You can also automate this from the Automation tab of Clop's settings by creating an image shortcut that uses the Convert to WEBP action, and set that shortcut to run on clipboard or folders.
![Screenshot 2024-09-20 at 5 35 11 PM](https://github.com/user-attachments/assets/341f24bc-593a-4b25-8dae-086b61b893b0)

Could you please show me how to in detail?

I want clop to convert all images to webp automatically and I only see "convert to jpeg" and "convert to png"

**Comment by rgraemer** [comment]
I would welcome auto-conversions to WebP or AVIF (Apple includes an AV1 Decoder in its latest devices) for its size and quality. 
https://bitmovin.com/blog/av1-playback-support/

**Comment by alin23** [comment]
This is now possible to do more easily using the included **Convert to WEBP** automation:

![Clop-007021-Tuesday-14-39](https://github.com/user-attachments/assets/9be00a7c-5acd-4baf-991a-f82c56b9e779)

Inside the shortcut, you'll find that you can change the format to AVIF if you want:

![Shortcuts-007023-Tuesday-14-41](https://github.com/user-attachments/assets/7429864a-c79f-4f06-bd9e-090cca71861d)

**Comment by b3rdma** [comment]
I was missing that in the shortcuts app, I have to create a folder, name it Clop, then add the created shortcuts to that folder. Finally got it to show up in the app. First time using shortcuts so had no idea; maybe instructions for this step?

Thanks for the steer and great app. Very slick indeed. Until now I have been using my own scripts but I like this app and it's looks.

**Comment by alin23** [comment]
> I was missing that in the shortcuts app, I have to create a folder, name it Clop, then add the created shortcuts to that folder. Finally got it to show up in the app. First time using shortcuts so had no idea; maybe instructions for this step?
> 
> Thanks for the steer and great app. Very slick indeed. Until now I have been using my own scripts but I like this app and it's looks.

Thank you for the kind words! 

The Clop folder should not have been necessary, that should be optional in case you want to only have specific Shortcuts appear in Clop's dropdown. I'll take a look to see if I might have made a mistake there.

**Comment by b3rdma** [comment]
Then it might be a me thing; so many customised settings/configs maybe I have inadvertently created a conflict with the shortcuts app. No idea. I know it works now and I have a very efficient workflow set up with CleanShotX. Great tool and I look forward to trying it with videos/pdfs too.
