### ISSUE TITLE
Crash on NSProgress data race when using CLI

### ISSUE THREAD

**Issue by NBaLogn** [FuzzyIdeas/Clop#37]
Here's the relevant settings for the app.
<img width="644" alt="SCR-20240922-quhd" src="https://github.com/user-attachments/assets/856da353-bdda-44f7-aeda-3a18a5b48240">
<img width="695" alt="SCR-20240922-qtmu" src="https://github.com/user-attachments/assets/50a9f5d1-dd31-44b8-9fff-54f60a5f7778">
<img width="653" alt="SCR-20240922-qvwx" src="https://github.com/user-attachments/assets/6ef70f9a-d9ef-437d-966a-78efa2b5ac71">

I just downloaded the app for a few days, and was using it to optimize a few folders of mixed files (PDF and videos). Since there's a lot of files, I used the CLI command "clop optimize -garn *" to optimize aggressively for all files in the folder and subfolders, no progress bar in the terminal but in the GUI instead. 

However, sometimes while optimizing a video, the terminal shows this error
<img width="1258" alt="SCR-20240922-oauu" src="https://github.com/user-attachments/assets/1f772011-0fd6-4b46-8dc6-e32df12dd568"> which indicates process exit, while the GUI shows the process still works in the background, just that it skips that (those) item(s). 

After waiting for a while, it'd show that subsequent items in the folders would not be optimized, so I clicked on "Stop and clear", but then some items would be missing, not appearing anywhere. There appears to be attempts to recover from the app itself, but it still lost a lot of videos. 

I don't know if this is mainly a CLI bug, or just an app bug in general; I've mainly only used the CLI, and the majority of that bug appeared there. It could be that it's an app bug that could appear during background/clipboard optimization but I didn't encounter/notice.

I was able to restore them from Time Machine, but it seems this is a notable bug. If there's some workaround or some settings I set that lead to this result, please inform me.

**Comment by alin23** [comment]
Have you checked the backups folder? You can open it from the Clop menu bar icon. The videos should be there even if the operation failed. 

About the error, please have a look in `~/Library/Logs/DiagnosticReports` and see if you have any Clop related crash log. Send me any you can find.

**Comment by NBaLogn** [comment]
I checked a few times, there were a lot of files there, but weirdly most of the files I lost are not there. When I tried searching system-wide using Onyx, just before I used Time Machine, I actually got a few files from the hidden "private/var/folders/t6/[some-keys]/T/TemporaryItems" folder tho. 
<img width="1107" alt="SCR-20240923-prfs-3" src="https://github.com/user-attachments/assets/eeca0ddf-c960-45fa-98ea-0c63d7f46498">

And here's the zip of the reports, tho it's in a folder called "Retired", so I just zipped it up like that.
[Retired.zip](https://github.com/user-attachments/files/17104828/Retired.zip)

**Comment by alin23** [comment]
Looks like a thread safety issue on fetching and showing progress on the terminal:

```swift
Thread 2 Crashed:
0   libobjc.A.dylib               	       0x18e84bb78 objc_retain + 16
1   Foundation                    	       0x190883810 -[NSProgress localizedAdditionalDescription] + 60
2   ClopCLI                       	       0x1021382ac ProgressPrinter.printProgress() (in ClopCLI) (main.swift:1292) + 98988
3   ClopCLI                       	       0x102136d88 closure #1 in closure #1 in ProgressPrinter.addProgressSubscriber(url:progress:) (in ClopCLI) (main.swift:1246) + 93576
4   ClopCLI                       	       0x102163e69 thunk for @escaping @isolated(any) @callee_guaranteed @async () -> (@out A)specialized partial apply (in ClopCLI) + 1 + 278121
5   ClopCLI                       	       0x10213dfe9 specialized thunk for @escaping @isolated(any) @callee_guaranteed @async () -> (@out A) (in ClopCLI) (/<compiler-generated>:0) + 122857
6   ClopCLI                       	       0x102163e69 thunk for @escaping @isolated(any) @callee_guaranteed @async () -> (@out A)specialized partial apply (in ClopCLI) + 1 + 278121
7   libswift_Concurrency.dylib    	       0x2683c1035 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1
```

Adding `--no-progress` should fix this until I find the underlying problem and I release a new version.
