### ISSUE TITLE
Conflict with Final Cut Pro

### ISSUE THREAD

**Issue by sonarun** [FuzzyIdeas/Clop#38]
In Final Cut pro with Clop open, dragging a clip from the media browser to the timeline, Clop interacts with the gesture and Final Cut Pro "Exports XML" to the clipboard. You can see a popup briefly when doing the gesture. 

I don't know if there is a way to remove apps that Clop does not interact with. Often I will be collecting media for a project and using Clop at the same time to reduce the file sizes. So the two programs do compliment each other.

**Comment by alin23** [comment]
Unfortunately this seems to be the case with any app that accesses the `drag` pasteboard. I tested Yoink, Dropover, Dropshare, Dockside, all of them have the same problem and it happens on simply looking inside the pasteboard

I added logic to ignore drags from Final Cut if they contain xml data. It will be released soon in 2.7.0
