### ISSUE TITLE
Could this support macOS 12 (Monterey)?

### ISSUE THREAD

**Issue by huyz** [FuzzyIdeas/Clop#4]
Or is there some technical reason why macOS 12 can't be supported?

**Comment by alin23** [comment]
The technical reasons are the "menu bar" and "launch at login" APIs that were introduced in macOS 13. I wanted to use those and skip writing the boilerplate that I have in my other apps, for a much leaner code and app size.

It's possible to make it work on macOS 12 but I don't have the time or incentive to do that right now.

**Comment by huyz** [comment]
Fair enough. Thanks
