### ISSUE TITLE
Optimised video error

### ISSUE THREAD

**Issue by Scantraxx01** [FuzzyIdeas/Clop#41]
After optimising a video file I got errors on both Mac OS and Windows:

Windows:
![Screenshot 2024-10-28 211231](https://github.com/user-attachments/assets/fe56bc4d-1224-403e-861e-6576bf4d2d3a)

Mac OS:
![Screenshot 2024-10-28 at 21 13 12](https://github.com/user-attachments/assets/e6c430cf-469c-434e-953e-327915209275)

**Comment by alin23** [comment]
It's possible that the video was not encoded until the end, or it may have used an encoder that's not supported by Clop. You can find the original file in the backups folder:

![Firefox Developer Edition-006803-Tuesday-20-26](https://github.com/user-attachments/assets/1e909c20-ae59-4abb-a853-ac9696ef096e)

To find what went wrong, you'd have to stream logs using the following terminal command:

```sh
log stream --level debug --style compact --process Clop --predicate 'subsystem BEGINSWITH "com.lowtechguys.Clop"' | tee ~/Desktop/clop.txt
```

Then try optimising the file that failed. Then send me the `clop.txt` file from your Desktop.

I'll close this, we can continue the discussion on [Discord](https://discord.gg/99vACD8D5u) as this is not a specific issue of the code.
