### ISSUE TITLE
pro version?

### ISSUE THREAD

**Issue by luckman212** [FuzzyIdeas/Clop#5]
[release notes][1] say _"Completely free version before the Pro features were introduced..."_

where is the pro version? I couldn't find any mention of it anywhere...

[1]: https://github.com/FuzzyIdeas/Clop/releases/tag/v1

**Comment by alin23** [comment]
Damn how did you see this so quick? 

The Pro version is still in the works, preparing to release it in the following days. 

I thought no one watched this repo but I guess I should make a pre-release to explain some things before.

**Comment by alin23** [comment]
Posted some words on the upcoming version here: https://github.com/FuzzyIdeas/Clop/releases/tag/v2

**Comment by luckman212** [comment]
> _Damn how did you see this so quick?_

I was just following the repo 🙂

Thanks for posting the info, I'll keep an eye out for v2!

**Comment by alin23** [comment]
Clop v2 was just released ^_^ The website got an update as well: https://lowtechguys.com/clop
