### ISSUE TITLE
disable auto-optimize

### ISSUE THREAD

**Issue by valkenrath** [FuzzyIdeas/Clop#6]
at present, even with null watch paths and all hotkeys disabled, it seems ⌘ + c triggers an optimisation (bottom right popup appears)

this is undesirable:
- when the optimisation fails (often, possibly FUSE/NFS related), the source file is replaced with a 0 byte broken file
- when the optimization succeeds, the source file is replaced (!!) with clop's output, without my having 'approved' this - the only action taken was ⌘ + c

much more often than not, when copying, i don't want optimization to occur, for example if transferring full fat pictures from a camera to a network share - i want the originals!

ideal scenario (for my use case): clipboard copy does nothing by default, but can be manually instigated via defined hotkey (my choice of modifier + C, per Clop's settings pane), or even better, with a similar command that optimizes then pastes
is this possible? if so, please advise what i'm missing

further, more philosophically, is it sane to have (potentially, and at present empirically) destructive defaults?

fwiw, i'd find ($) value in this utility if it behaved as requested - an *on demand* background clipboard optimizer for images/gifs 

v2.0.3 ie latest, but also also Sonoma 14.0 Beta (23A5312d), possibly this is the problem?

**Comment by alin23** [comment]
By default Clop should only overwrite the clipboard image data, not the files themselves (this is when using Cmd-C which is enabled out of the box)

I tried to use non destructive sensible defaults, not sure what is going wrong in your case. Maybe can you send some detailed steps so I can test it myself?

v2.1.0 will soon have support for disabling the clipboard optimizer. It's already pushed, it needs more testing and a release. 

It will also have a drop zone for files in case optimizing manually by hotkey is not as intuitive. 

Optimizing on paste would be nice but it would need Accessibility permissions to stimulate the Cmd-V key combo. For now I'm trying to avoid asking for these permissions.

**Comment by alin23** [comment]
I did more testing and indeed, when copying an image from an app that places both the image data AND the image path, the original file gets modified. This is a bug, will be fixed in v2.1.0, thanks for letting me know about this!

**Comment by alin23** [comment]
Fixed in [v2.1.1](https://github.com/FuzzyIdeas/Clop/releases/tag/v2.1.1)

**Comment by diogox** [comment]
> Optimizing on paste would be nice but it would need Accessibility permissions to stimulate the Cmd-V key combo. For now I'm trying to avoid asking for these permissions.

I'm going to reopen this issue with an observation I made, and that prevented me from using the app.

In Finder, when you want to move files with the keyboard, you have to use `cmd+c` and then `cmd+option+v`. There's no `ctrl+x` and `ctrl+v` workflow like in Linux and Windows.

With Clop installed, when you `cmd+c` an image, it creates a new optimized version. And when you `cmd+option+v`, it moves the optimized version to the desired location, leaving the original in place.

While I'm glad the original is safe, this breaks the keyboard-driven workflow for moving files.

If the optimization was only pasted on `cmd+v`, that would solve the issue.

Personally, I'm fine with needing more permissions.

Wdyt?
