### ISSUE TITLE
Survey ImageOptim output and utilize best practices? And more...

### ISSUE THREAD

**Issue by ylluminate** [FuzzyIdeas/Clop#7]
Your tool caught me by surprise. It's very attractive to have the capacity to have optimized pasteboard/clipboard contents that are similarly converted to the most optimal format.

First, have you per chance performed a survey with [ImageOptim.app](https://imageoptim.com/mac) to perhaps ascertain if it's using any options / settings that are superior to what Clop presently does? Eg, I use these generally:
![settings](https://p153.p0.n0.cdn.getcloudapp.com/items/L1uv06R5/46fdb460-2d01-42b5-80c1-b8e5118fef91.png?v=b2e8a58ba84230123ca61e820045ff4f)

Secondly, I this doesn't seem immediately feasible, but long term I've been *DYING* to find a Skitch 1 (NOT 2) and NOT CleanShot (or others) clone. CleanShot guys are kinda close'ish, but after a couple years of begging, I don't think they'll ever warm up to a clone approach to Skitch. Making an outright clone of that would be pretty much the perfect / ideal annotation / capture app. There's a pretty large consensus to this if you look at old MacUpdate and other reviews and commentary. The UX was about as close to perfection as anyone has ever seen and if you were to make such a thing, you'd get my donation/purchase.

Third, a CloudApp (now known as Zight), but self hosted that you could integrate for file sharing into this kind of work flow would be the icing and bucket-o-cherries on top.

**Comment by alin23** [comment]
Hi! Thank you!

Yes, actually Clop is for me a better successor to ImageOptim in the workflows I use the most. **Strip EXIF metadata** is coming in the next version, and I'm already using the fastest optimisers: `pngquant`, `jpegoptim` and `gifsicle`

This is what I arrived with ImageOptim as well after using it continuosly for the past years. All those Zopfli, OxiPNG etc. options were only making the optimisation process slower, and rarely brought size savings that would be worth the time.

I'm also custom compiling all these optimisers for both Apple Silicon and Intel. ImageOptim seems to have published that as a beta for now: https://imageoptim.com/changelog.html

I'm not trying to create a screenshot app here though, I am happy enough with Cleanshot and really don't have time or the need to replicate Skitch. Thanks for the hint though, I'll keep it in mind for the future!

About file sharing, I'm planning to collaborate with the DropShare dev and integrate with their [DropShare Cloud](https://dropshare.cloud/sites/plans) offering. If I would do it on my own, it would probably cost more than $2/month for a less polished UX.

**Comment by ylluminate** [comment]
Thanks for the info / sharing your experience! 

Given that and general strange resistance in some areas re: the latter, I might just build a Skitch clone myself with V. It would be a fun project and I believe I could make it cross platform with a single codebase that way. Paweł is great, but I just am not feeling it for CleanShot or anything for that matter after all these years. I do believe I've tried *everything*. It would at least be a fun long term project. Also a private self storage option would be of value given the state of things.

**Comment by alin23** [comment]
I would like to add private storage support with Backblaze, so that there is at least one free alternative to the Dropshare integration. Would that fit your use case?

Can I find Skitch 1 anywhere to test it on Ventura? For me Cleanshot really is a powerhouse, but you made me curious as to what Skitch had to offer. 

Hope I did not appear as hostile, I'm not resistant to the Skitch idea, I just really do not have time for another app anymore. 

A screencapture and annotation app can be very complex. I am the sole developer of all the apps you see on [The low-tech guys](https://lowtechguys.com/) and after the [case studies Reddit post](https://old.reddit.com/r/macapps/comments/15zas8f/clop_license_giveaway_tell_me_about_your_workflow/), I've been constantly working on the Clop backlog and I'm still buried in tasks. 

If you do get to build such an app in V, I'd love to see it's source code! A real cross platform language for GUI apps is something I am still looking for.

**Comment by ylluminate** [comment]
Hectic day. Well, I will have to try to dig up some videos and/or screenshots I made long ago to document everything for Paweł. It should run alright (I think I still have old binaries archived floating around) on a Mojave vm.

No, not hostile, just a bit and understandably dismissive. I know what it's like to be overly overwhelmed. I myself am barely keeping my head above water with all of my life commitments at present, so no judgement from this end! 🤣 Also cultures are different and we communicate different even with the "same" cultures. Totally get it - even if many/most(?) others may not.

Yeah, I think V can do it with some love and effort. V is an awesome language and the community is awesome. Some great things are happening from the choice few who are working on hammering things out at present. Beats the crap outta Rust and, well, all the other options really at the moment if/when you grok the vision and effort.
