### ISSUE TITLE
Clop & Clipboard: redundant optimising when saving screenshots 

### ISSUE THREAD

**Issue by roelvangils** [FuzzyIdeas/Clop#9]
I use Clop in combination with CleanShot. I have Optimise Clipboard turned on, as well as the option where all the files I save in `~/Screenshots` are processed. However, when I decide to save a screenshot (<kbd>⌘+S</kbd> in CleanShot) what would be nice if Clop could somehow detect that it is in fact the same image data and use the clipboard data for saving. Right now it seems like a bit of CPU usage for nothing.

Here's a little video to illustrate when I mean:

https://github.com/FuzzyIdeas/Clop/assets/103744/23c6549d-d230-4f3c-b2b0-b6eca2540200

**Comment by alin23** [comment]
I think I managed to fix this. I can only hope I didn't break something else.

It will be released in v2.2.0 soon
